// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"context"
)

type Querier interface {
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	GetInvoiceByID(ctx context.Context, id int64) (Invoice, error)
	GetInvoicesByUserID(ctx context.Context, arg GetInvoicesByUserIDParams) ([]Invoice, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Invoice, error)
}

var _ Querier = (*Queries)(nil)
