// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"context"
)

type Querier interface {
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	GetInboundTransfers(ctx context.Context, arg GetInboundTransfersParams) ([]Transfer, error)
	GetOutboundTransfers(ctx context.Context, arg GetOutboundTransfersParams) ([]Transfer, error)
	GetTransferByID(ctx context.Context, id int64) (Transfer, error)
	GetTransfersBetweenUsers(ctx context.Context, arg GetTransfersBetweenUsersParams) ([]Transfer, error)
}

var _ Querier = (*Queries)(nil)
